# Generated by Django 6.0.1 on 2026-06-15 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_bidul_mois_int_lieu_coord_index'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaireSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_text', models.TextField(default='Vous etes un groupe, un tourneur, un bar, une salle de concert et souhaitez annoncer un evenement dans le Bidul ? Remplissez ce formulaire.', verbose_name='Texte introduction')),
                ('help_email', models.CharField(blank=True, default='Email a contacter en cas de question.', max_length=300, verbose_name='Aide champ email')),
                ('help_date', models.CharField(blank=True, default='Date de l evenement.', max_length=300, verbose_name='Aide champ date')),
                ('help_heure', models.CharField(blank=True, default='Exemple : 20h30', max_length=300, verbose_name='Aide champ heure')),
                ('help_lieu', models.CharField(blank=True, default='Selectionnez le lieu ou proposez-en un nouveau.', max_length=300, verbose_name='Aide champ lieu')),
                ('help_prix', models.CharField(blank=True, default='Gratuit, prix libre, 10 EUR...', max_length=300, verbose_name='Aide champ prix')),
                ('show_description', models.BooleanField(default=True, verbose_name='Afficher Description')),
                ('show_date_fin', models.BooleanField(default=True, verbose_name='Afficher Date fin')),
                ('show_heure_fin', models.BooleanField(default=True, verbose_name='Afficher Heure fin')),
                ('show_categorie', models.BooleanField(default=True, verbose_name='Afficher Categorie')),
                ('show_url', models.BooleanField(default=True, verbose_name='Afficher Lien web')),
            ],
            options={
                'verbose_name': 'Formulaire evenements',
            },
        ),
        migrations.RemoveIndex(
            model_name='lieu',
            name='agenda_lieu_latitud_6bb036_idx',
        ),
        migrations.AlterField(
            model_name='bidul',
            name='mois',
            field=models.CharField(help_text='Nom du mois (ex: décembre)', max_length=20),
        ),
        migrations.AddField(
            model_name='formulairesettings',
            name='site',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site'),
        ),
    ]
