# Generated by Django 6.0.1 on 2026-06-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_formulairesettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSheetMensuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(verbose_name='Annee')),
                ('mois', models.PositiveIntegerField(verbose_name='Mois (1-12)')),
                ('url', models.URLField(max_length=500, verbose_name='URL du Google Sheet')),
            ],
            options={
                'verbose_name': 'Google Sheet mensuel',
                'verbose_name_plural': 'Google Sheets mensuels',
                'ordering': ['-annee', '-mois'],
                'unique_together': {('annee', 'mois')},
            },
        ),
    ]
